import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import "./globals.css";
import Menu from "@/features/routes/home/Menu";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div className="flex items-start min-h-screen bg-white">
            <Menu />
              {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
