import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import "./globals.css";
import Menu from "@/features/routes/home/Menu";
import React from "react";
import { Box } from "@chakra-ui/react";
import ToastProvider from "./ToastProvider";
import QuestDetail from "@/features/routes/quest/questDetail";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <Provider>
          <Box display={"flex"} flexDirection={"row"} minHeight={"100vh"}>
            {/* <div className="flex items-start min-h-screen bg-white "> */}
            <Menu />
            <ToastProvider>{children}</ToastProvider>
          </Box>
        </Provider>
      </body>
    </html>
  );
}
