import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import "./globals.css";
import Menu from "@/features/routes/home/Menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Menu />
          {children}
        </Provider>
      </body>
    </html>
  );
}
